<?php

/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Perspective\ReviewTree\Api\Data\ReviewFieldsEx;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var HeroiconsSolid $heroiconsSolid */
$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);

$format = $block->getDateFormat() ?: \IntlDateFormatter::SHORT;

$reviews = $block->getData('items');
$review = $block->getData('review');
$children = array_key_exists($review->getId(), $reviews) ? $reviews[$review->getId()] : [];
?>

<div itemscope itemprop="review" itemtype="http://schema.org/Review"
    class="border-b pb-4 my-4 border-container last:border-0 last:mb-0">
    <?php if (count($review->getRatingVotes())): ?>
        <div class="table">
        <?php foreach ($review->getRatingVotes() as $vote): ?>
            <?php
                $rating = $vote->getPercent();
                $ratingSteps = 5;
                $starsFilled = is_numeric($rating) ? floor($rating / 100 * $ratingSteps) : 0;
                $starsEmpty = floor($ratingSteps - $starsFilled);
            ?>
            <div class="table-row" itemprop="reviewRating" itemscope itemtype="http://schema.org/Rating">
                <div class="table-cell pr-6 align-middle text-left">
                    <?= $escaper->escapeHtml($vote->getRatingCode()) ?>
                </div>
                <span class="hidden" itemprop="ratingValue"><?= /** @noEscape */ $starsFilled; ?></span>
                <div class="flex flex-row">
                    <?php $i = 0; ?>
                    <?php while ($i < $starsFilled): ?>
                        <?= $heroiconsSolid->starHtml('text-yellow-400'); ?>
                        <?php $i++; ?>
                    <?php endwhile; ?>
                    <?php $i = 0; ?>
                    <?php while ($i < $starsEmpty): ?>
                        <?= $heroiconsSolid->starHtml('text-gray-400'); ?>
                        <?php $i++; ?>
                    <?php endwhile; ?>
                </div>
            </div>
        <?php endforeach; ?>
        </div>
    <?php endif; ?>
    <div class="text-lg my-2" itemprop="name">
        <?= $escaper->escapeHtml($review->getTitle()) ?>
    </div>
    <div>
        <span><?= $escaper->escapeHtml(__('Review by')) ?></span>
        <strong itemprop="author">
            <?= $escaper->escapeHtml($review->getNickname()) ?>
            <?php if ($review->getData(ReviewFieldsEx::IS_AUTHOR_VERIFIED)): ?>
                <?= $heroicons->badgeCheckHtml('inline-block ml-2 text-green-500') ?>
            <?php endif; ?>
        </strong>
        <span class="text-gray-700 inline-block ml-2">
            <time
                itemprop="datePublished"
                datetime="
                <?= $escaper->escapeHtmlAttr(
                    $block->formatDate(
                        $review->getCreatedAt(),
                        $format
                    )
                ); ?>">
                <?= $escaper->escapeHtml(
                    $block->formatDate($review->getCreatedAt(), $format)
                ) ?>
            </time>
        </span>
    </div>
    <div class="mt-2" itemprop="description">
        <?= /* @noEscape */ nl2br($escaper->escapeHtml($review->getDetail())) ?>
    </div>

    <?php if (!empty($children)): ?>
    <div class="mt-3 ml-6 pl-3 border-l-2 border-gray-300">
        <?php foreach ($children as $child) {
            $childItemBlock = $block->getParentBlock()
                                    ->getChildBlock('item')
                                    ->setData('items', $reviews)
                                    ->setData('review', $child);
            echo $childItemBlock->toHtml();
        } ?>
    </div>
    <?php endif; ?>

    <div class="mt-10" x-data="{open: false}">
        <a href="#" @click.prevent="open = !open">
            <?= $heroiconsSolid->pencilHtml('inline-block mr-2') ?>
            <?= __('Answer') ?>
        </a>
        <template x-if="open">
            <?= $block->getChildBlock('form')->setData(ReviewFieldsEx::PARENT_ID, $review->getId())->toHtml() ?>
        </template>
    </div>
</div>
